import fs from 'fs';
import path from 'path';
import { createWriteStream } from 'fs';
import { pipeline } from 'stream/promises';

function normalizeUrl(url) {
  if (url.startsWith('//')) return `https:${url}`;
  return url;
}

function safeFilename(family, url) {
  const ext = path.extname(new URL(normalizeUrl(url)).pathname) || '.woff2';
  const base = family.replace(/['"]/g, '').replace(/\s+/g, '-').toLowerCase().slice(0, 40);
  const hash = Buffer.from(url).toString('base64url').slice(0, 8);
  return `${base}-${hash}${ext}`;
}

async function download(url, dest) {
  const res = await fetch(normalizeUrl(url), { redirect: 'follow' });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  await pipeline(res.body, createWriteStream(dest));
}

/**
 * @param {{ family: string, urls: string[] }[]} fonts
 * @param {string} publicFontsDir
 */
export async function materializeFonts(fonts, publicFontsDir) {
  fs.mkdirSync(publicFontsDir, { recursive: true });
  /** @type {{ family: string, files: { url: string, local: string }[] }[]} */
  const manifest = [];

  for (const face of fonts) {
    const family = face.family.replace(/['"]/g, '');
    const files = [];
    for (const url of face.urls.slice(0, 2)) {
      const name = safeFilename(family, url);
      const dest = path.join(publicFontsDir, name);
      if (!fs.existsSync(dest)) {
        try {
          await download(url, dest);
        } catch (e) {
          console.warn('font skip', family, String(e.message || e));
          continue;
        }
      }
      files.push({ url, local: `/fonts/wix/${name}` });
    }
    if (files.length) manifest.push({ family, files });
  }

  const cssLines = manifest.flatMap(({ family, files }) => {
    const woff2 = files.find((f) => f.local.endsWith('.woff2'));
    const woff = files.find((f) => f.local.endsWith('.woff'));
    if (!woff2 && !woff) return [];
    const src = [woff2 && `url('${woff2.local}') format('woff2')`, woff && `url('${woff.local}') format('woff')`]
      .filter(Boolean)
      .join(', ');
    return [`@font-face { font-family: '${family}'; src: ${src}; font-display: swap; }`];
  });

  const cssPath = path.join(publicFontsDir, 'wix-blank10.css');
  fs.writeFileSync(
    cssPath,
    `/* Auto-generated by import-wix */\n${cssLines.join('\n')}\n.b10 { font-family: 'Alan Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; }\n`
  );

  return { manifest, cssPath: '/fonts/wix/wix-blank10.css' };
}
